### ISSUE TITLE
사용자 추가를 시작할때 폼 초기화

### ISSUE THREAD

**Issue by UniverseHan** [onlyhisson/first_android#9]
사용자 추가를 시작할때 입력 폼은 새로 비워져 있어야 한다.

## 시나리오 1
- 사용자 추가 버튼 클릭
- 입력 폼에 내용 작성
- 취소 클릭
- 다시 사용자 추가 버튼 클릭
- 폼은 비워져 있어야 함.

## 시나리오 2
- 사용자 추가 버튼 클릭
- 내용 작성
- 완료 
- 사용자 뷰에서 다시 추가 버튼 클릭
- 기존 내용은 폼에 남아 있으면 안됨.

**Comment by onlyhisson** [comment]
위에 기능은 이미 되어있고 새로운 이슈 생성
